FROM node:17

# Create app directory, this is in our container/in our image
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

RUN npm run build bsocial-notifications-microservice

CMD [ "node", "dist/apps/bsocial-notifications-microservice/main" ]
