export const enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_EMAIL_OR_USERNAME_OR_PASSWORD = 'INVALID_EMAIL_OR_USERNAME_OR_PASSWORD',
  EMAIL_OR_USERNAME_ALREADY_EXISTS = 'EMAIL_OR_USERNAME_ALREADY_EXISTS',
  PASSWORD_AND_PASSWORD_CONFIRMATION_DO_NOT_MATCH = 'PASSWORD_AND_PASSWORD_CONFIRMATION_DO_NOT_MATCH',
  CANNOT_ACCESS_POSTS_OF_THIS_USER = 'CANNOT_ACCESS_POSTS_OF_THIS_USER',
  CANNOT_ACCESS_THIS_POST_AND_ITS_COMMENTS = 'CANNOT_ACCESS_THIS_POST_AND_ITS_COMMENTS',
}
